name: Build and Sign Flutter macOS App (Lando Version)

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'
        
    - name: Set up working directory
      run: cd flutter_furl
      
    - name: Get dependencies
      run: |
        cd flutter_furl
        flutter pub get
        
    - name: Build macOS app
      run: |
        cd flutter_furl
        flutter build macos --release
        
    - name: Sign and notarize macOS app
      if: github.event_name != 'pull_request'
      uses: lando/code-sign-action@v3
      with:
        file: flutter_furl/build/macos/Build/Products/Release/flutter_furl.app
        certificate-data: ${{ secrets.MACOS_CODESIGN_CERT }}
        certificate-password: ${{ secrets.MACOS_CODESIGN_CERT_PASSWORD }}
        apple-team-id: ${{ secrets.MACOS_TEAM_ID }}
        apple-notary-user: ${{ secrets.MACOS_APPLE_ID }}
        apple-notary-password: ${{ secrets.MACOS_APPLE_ID_PASSWORD }}
        apple-product-id: com.atsign.flutterFurl
        options: --options runtime --entitlements entitlements.plist
        
    - name: Create entitlements file
      run: |
        cat > entitlements.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>com.apple.security.app-sandbox</key>
          <true/>
          <key>com.apple.security.network.client</key>
          <true/>
          <key>com.apple.security.files.user-selected.read-write</key>
          <true/>
          <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
          <true/>
        </dict>
        </plist>
        EOF
        
    - name: Upload signed app
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: flutter-furl-macos-signed
        path: flutter_furl/build/macos/Build/Products/Release/flutter_furl.app
