name: furl
description: Secure file sharing with multi-layer encryption and client-side decryption
version: 1.1.0
repository: https://github.com/cconstab/furl

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  at_client: ^3.7.0
  at_onboarding_cli: ^1.12.0
  at_utils: ^3.0.18
  args: ^2.6.0
  encrypt: ^5.0.3
  http: ^1.2.1
  dio: ^5.4.0
  crypto: ^3.0.3
  random_string: ^2.3.1
  uuid: ^4.0.0
  pointycastle: ^3.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  furl: furl
  furl-server: furl_server
