name: Flutter Android Build

on:
  push:
    branches: [ main, autobuild ]
    paths:
      - 'flutter_furl/**'
      - '.github/workflows/flutter-android.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'flutter_furl/**'
      - '.github/workflows/flutter-android.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-android:
    name: Build Android APK/AAB
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: flutter_furl
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'
        channel: 'stable'
        cache: true

    - name: Get Flutter dependencies
      run: |
        # Pin at_client_mobile to avoid incompatible 3.3.0
        sed -i.bak 's/at_client_mobile: \^3\.2\.26/at_client_mobile: 3.2.26/' pubspec.yaml
        flutter pub get

    - name: Fix Android namespace issues
      run: |
        chmod +x fix_namespaces.sh
        ./fix_namespaces.sh

    - name: Analyze Flutter code
      run: flutter analyze --fatal-infos

    - name: Run Flutter tests
      run: flutter test

    - name: Build APK (debug)
      run: flutter build apk --debug

    - name: Build APK (release)
      run: flutter build apk --release

    - name: Build AAB (release)
      run: flutter build appbundle --release

    - name: Upload APK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-apk-${{ github.sha }}
        path: |
          flutter_furl/build/app/outputs/flutter-apk/app-debug.apk
          flutter_furl/build/app/outputs/flutter-apk/app-release.apk
        retention-days: 30

    - name: Upload AAB artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-aab-${{ github.sha }}
        path: flutter_furl/build/app/outputs/bundle/release/app-release.aab
        retention-days: 30

    - name: Test APK installation (debug)
      run: |
        # Verify APK was created and has correct structure
        if [ -f "build/app/outputs/flutter-apk/app-debug.apk" ]; then
          echo "✓ Debug APK created successfully"
          ls -la build/app/outputs/flutter-apk/app-debug.apk
        else
          echo "✗ Debug APK not found"
          exit 1
        fi

    - name: Test APK installation (release)
      run: |
        # Verify release APK was created and has correct structure
        if [ -f "build/app/outputs/flutter-apk/app-release.apk" ]; then
          echo "✓ Release APK created successfully"
          ls -la build/app/outputs/flutter-apk/app-release.apk
        else
          echo "✗ Release APK not found"
          exit 1
        fi
