name: Build and Sign Flutter macOS App (Lando Version)

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'
        
    - name: Set up working directory
      run: cd flutter_furl
      
    - name: Get dependencies
      run: |
        cd flutter_furl
        flutter pub get
        
    - name: Build macOS app
      run: |
        cd flutter_furl
        # Build universal binary (arm64 + x86_64)
        flutter build macos --release --dart-define=FLUTTER_TARGET_PLATFORM=darwin
        
        # Verify the binary architectures
        echo "Built app architectures:"
        file build/macos/Build/Products/Release/flutter_furl.app/Contents/MacOS/flutter_furl
        lipo -info build/macos/Build/Products/Release/flutter_furl.app/Contents/MacOS/flutter_furl || echo "Not a universal binary"
        
    - name: Create entitlements file
      run: |
        cat > entitlements.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>com.apple.security.app-sandbox</key>
          <true/>
          <key>com.apple.security.network.client</key>
          <true/>
          <key>com.apple.security.files.user-selected.read-write</key>
          <true/>
          <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
          <true/>
        </dict>
        </plist>
        EOF
        
    - name: Debug secrets availability
      run: |
        echo "Checking secret availability..."
        echo "MACOS_CODESIGN_CERT length: ${#MACOS_CODESIGN_CERT}"
        echo "MACOS_CODESIGN_CERT_PASSWORD length: ${#MACOS_CODESIGN_CERT_PASSWORD}"
        echo "MACOS_TEAM_ID length: ${#MACOS_TEAM_ID}"
        echo "MACOS_APPLE_ID length: ${#MACOS_APPLE_ID}"
        echo "MACOS_APPLE_ID_PASSWORD length: ${#MACOS_APPLE_ID_PASSWORD}"
        echo "MACOS_SIGNING_IDENTITY length: ${#MACOS_SIGNING_IDENTITY}"
      env:
        MACOS_CODESIGN_CERT: ${{ secrets.MACOS_CODESIGN_CERT }}
        MACOS_CODESIGN_CERT_PASSWORD: ${{ secrets.MACOS_CODESIGN_CERT_PASSWORD }}
        MACOS_TEAM_ID: ${{ secrets.MACOS_TEAM_ID }}
        MACOS_APPLE_ID: ${{ secrets.MACOS_APPLE_ID }}
        MACOS_APPLE_ID_PASSWORD: ${{ secrets.MACOS_APPLE_ID_PASSWORD }}
        MACOS_SIGNING_IDENTITY: ${{ secrets.MACOS_SIGNING_IDENTITY }}
        
    - name: Sign macOS app (Custom Approach)
      if: github.event_name != 'pull_request'
      env:
        MACOS_CODESIGN_CERT: ${{ secrets.MACOS_CODESIGN_CERT }}
        MACOS_CODESIGN_CERT_PASSWORD: ${{ secrets.MACOS_CODESIGN_CERT_PASSWORD }}
        MACOS_SIGNING_IDENTITY: ${{ secrets.MACOS_SIGNING_IDENTITY }}
        MACOS_KEYCHAIN_PASSWORD: build123
      run: |
        echo "=== Setting up signing environment ==="
        
        # Decode and import certificate
        echo "$MACOS_CODESIGN_CERT" | base64 --decode > certificate.p12
        
        # Create keychain
        KEYCHAIN_PATH="$HOME/Library/Keychains/build.keychain"
        security create-keychain -p "$MACOS_KEYCHAIN_PASSWORD" build.keychain
        security set-keychain-settings -lut 21600 build.keychain
        security unlock-keychain -p "$MACOS_KEYCHAIN_PASSWORD" build.keychain
        security list-keychain -d user -s build.keychain
        
        # Import certificate
        security import certificate.p12 -P "$MACOS_CODESIGN_CERT_PASSWORD" -A -t cert -f pkcs12 -k build.keychain
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$MACOS_KEYCHAIN_PASSWORD" build.keychain
        
        echo "Available signing identities:"
        security find-identity -v -p codesigning
        
        APP_PATH="flutter_furl/build/macos/Build/Products/Release/flutter_furl.app"
        
        # Sign with simple approach
        echo "Signing app bundle..."
        codesign \
          --sign "$MACOS_SIGNING_IDENTITY" \
          --force \
          --deep \
          --options runtime \
          --timestamp \
          --entitlements entitlements.plist \
          --verbose \
          "$APP_PATH"
        
        # Verify signature
        echo "Verifying signature..."
        codesign --verify --deep --strict --verbose=2 "$APP_PATH"
        
        echo "✅ Signing completed successfully"
        
    - name: Notarize macOS app
      if: github.event_name != 'pull_request'
      env:
        MACOS_APPLE_ID: ${{ secrets.MACOS_APPLE_ID }}
        MACOS_TEAM_ID: ${{ secrets.MACOS_TEAM_ID }}
        MACOS_APPLE_ID_PASSWORD: ${{ secrets.MACOS_APPLE_ID_PASSWORD }}
      run: |
        echo "=== macOS App Notarization ==="
        
        APP_PATH="flutter_furl/build/macos/Build/Products/Release/flutter_furl.app"
        
        # Create archive for notarization
        echo "Creating archive for notarization..."
        cd flutter_furl/build/macos/Build/Products/Release/
        zip -r flutter_furl-for-notarization.zip flutter_furl.app/
        
        echo "Submitting app for notarization..."
        SUBMISSION_ID=$(xcrun notarytool submit flutter_furl-for-notarization.zip \
          --apple-id "$MACOS_APPLE_ID" \
          --team-id "$MACOS_TEAM_ID" \
          --password "$MACOS_APPLE_ID_PASSWORD" \
          --wait \
          --output-format json | jq -r '.id // empty')
        
        if [ -z "$SUBMISSION_ID" ]; then
          echo "❌ Failed to get submission ID"
          exit 1
        fi
        
        echo "Submission ID: $SUBMISSION_ID"
        
        # Check notarization status
        NOTARY_STATUS=$(xcrun notarytool info "$SUBMISSION_ID" \
          --apple-id "$MACOS_APPLE_ID" \
          --team-id "$MACOS_TEAM_ID" \
          --password "$MACOS_APPLE_ID_PASSWORD" \
          --output-format json | jq -r '.status // empty')
        
        echo "Notarization status: $NOTARY_STATUS"
        
        if [ "$NOTARY_STATUS" != "Accepted" ]; then
          echo "❌ Notarization failed with status: $NOTARY_STATUS"
          echo "Getting detailed logs..."
          xcrun notarytool log "$SUBMISSION_ID" \
            --apple-id "$MACOS_APPLE_ID" \
            --team-id "$MACOS_TEAM_ID" \
            --password "$MACOS_APPLE_ID_PASSWORD" || true
          exit 1
        fi
        
        echo "✓ Notarization completed successfully"
        
        # Staple the notarization ticket
        echo "Stapling notarization ticket..."
        if xcrun stapler staple flutter_furl.app; then
          echo "✓ Stapling successful"
          xcrun stapler validate flutter_furl.app
        else
          echo "❌ Stapling failed"
        fi
        
        cd ../../../../../
        
    - name: Upload signed app
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: flutter-furl-macos-signed
        path: flutter_furl/build/macos/Build/Products/Release/flutter_furl.app
